# Generated by Django 2.2.1 on 2019-05-15 02:48

from django.db import migrations, models
import shop.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, choices=[('Tommy Hilfiger', 'Tommy Hilfiger'), ("Levi's", 'Levis'), ('Calvin Klein', 'Calvin Klein'), ('Ralph Lauren', 'Ralph Lauren')], max_length=50, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to=shop.utils.upload_image_path)),
                ('image_2', models.ImageField(default='default.jpg', upload_to=shop.utils.upload_image_path)),
                ('image_3', models.ImageField(default='default.jpg', upload_to=shop.utils.upload_image_path)),
                ('price', models.DecimalField(decimal_places=2, default=11.0, max_digits=9)),
                ('category', models.CharField(blank=True, choices=[('Tshirt', 'Tshirt'), ('Shoes', 'Shoes'), ('Trousers', 'Trousers'), ('Jackets', 'Jackets'), ('Shirts', 'Shirts')], max_length=50, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=9)),
                ('comments', models.ManyToManyField(blank=True, to='comments.Comment')),
            ],
        ),
    ]
